# Generated by Django 4.1.7 on 2023-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_Phone', models.IntegerField(blank=True, null=True)),
                ('Bio', models.TextField()),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='doctors')),
            ],
        ),
    ]
