# Generated by Django 4.1.7 on 2023-07-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='Specialty',
            new_name='Speciality',
        ),
    ]
