# Generated by Django 4.1.7 on 2023-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_rename_specialty_doctordb_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_Phone', models.IntegerField(blank=True, null=True)),
                ('Bio', models.TextField()),
                ('Assigned_Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='doctors')),
            ],
        ),
    ]
