# Generated by Django 4.1.7 on 2023-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_nursedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursedb',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='nurses'),
        ),
    ]
