# Generated by Django 4.1.7 on 2023-08-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_alter_nursedb_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Department_Image', models.ImageField(blank=True, null=True, upload_to='categoryimage')),
            ],
        ),
    ]
