# Generated by Django 4.1.7 on 2023-08-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_departmentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='Department_Image',
            field=models.ImageField(blank=True, null=True, upload_to='departments'),
        ),
    ]
