# Generated by Django 4.1.7 on 2023-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_alter_departmentdb_department_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='Speciality',
            new_name='Department_Name',
        ),
    ]
