# Generated by Django 4.1.7 on 2023-08-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0007_rename_speciality_doctordb_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='Department_Name',
            new_name='Speciality',
        ),
    ]
