# Generated by Django 4.1.7 on 2023-08-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0008_rename_department_name_doctordb_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordb',
            old_name='Speciality',
            new_name='Department_Name',
        ),
    ]
