# Generated by Django 4.1.7 on 2023-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0010_alter_departmentdb_description_alter_doctordb_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_Phone', models.IntegerField(blank=True, null=True)),
                ('Medical_History', models.CharField(blank=True, max_length=100, null=True)),
                ('Admitted_Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Insurance_Information', models.CharField(blank=True, max_length=100, null=True)),
                ('Assigned_Doctor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
