# Generated by Django 4.1.7 on 2023-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0012_medicinedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='Bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedb',
            name='Description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nursedb',
            name='Bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdb',
            name='Medical_History',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
