# Generated by Django 4.1.7 on 2023-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0013_alter_departmentdb_description_alter_doctordb_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='Bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedb',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nursedb',
            name='Bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
