# Generated by Django 4.1.7 on 2023-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0014_alter_departmentdb_description_alter_doctordb_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLoginDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Re_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
