# Generated by Django 4.1.7 on 2023-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='registrationimages'),
        ),
    ]
