# Generated by Django 4.1.7 on 2023-08-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_medicinecartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinecartdb',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinecartdb',
            name='Medicine_Image',
            field=models.ImageField(blank=True, null=True, upload_to='cartimages'),
        ),
    ]
