# Generated by Django 4.1.7 on 2023-08-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_medicinecartdb_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinecartdb',
            name='Medicine_Image',
        ),
    ]
