# Generated by Django 4.1.7 on 2023-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_medicinecartdb_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.CharField(blank=True, max_length=100, null=True)),
                ('Cname', models.CharField(blank=True, max_length=100, null=True)),
                ('Cnum', models.IntegerField(blank=True, null=True)),
                ('Expm', models.CharField(blank=True, max_length=100, null=True)),
                ('Expyear', models.IntegerField(blank=True, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
