# Generated by Django 4.1.7 on 2023-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_checkout_checkoutdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Cname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Cnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Expm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Expyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
